/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cc_xsl_coolweather_CMakeTest */

#ifndef _Included_com_cc_xsl_coolweather_CMakeTest
#define _Included_com_cc_xsl_coolweather_CMakeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cc_xsl_coolweather_CMakeTest
 * Method:    stringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cc_xsl_coolweather_CMakeTest_stringFromC
        (JNIEnv *, jclass);

/*
 * Class:     com_cc_xsl_coolweather_CMakeTest
 * Method:    stringFromCpp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cc_xsl_coolweather_CMakeTest_stringFromCpp
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
