/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cc_xsl_coolweather_TestC */

#ifndef _Included_com_cc_xsl_coolweather_TestC
#define _Included_com_cc_xsl_coolweather_TestC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cc_xsl_coolweather_TestC
 * Method:    fromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cc_xsl_coolweather_TestC_fromC
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
